### DISCUSSION TITLE
How to insert line break in contents of tooltip

### DISCUSSION THREAD

**Discussion by muthubentley** [iTwin/iTwinUI#1121] [Q&A] [answered]
How to insert line break in contents of tooltip
I tried adding &#10; in the content and added the white-space: pre-wrap; but it isnt breaking to next line

tsx:
```jsx
<Tooltip content="simple &#10; tooltip" className="customtooltip">
              <Slider min={-1000} max={1000} step={10} />
            </Tooltip>
```
css:
```css
.customtooltip{
  text-align: left;
  white-space: pre-wrap;
}
```
