### ISSUE TITLE
Add CSS fallback handling of broken UserIcon images

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#129]
#### Feature

Add CSS handling of broken user-icon images with syled and colored user abbreviations.

Description with possible css solution in https://github.com/iTwin/iTwinUI-react/discussions/98.

#### Examples

Something like below did work, however the background color is always present so the image MUST be covering the background, not sure how else we could pass on the `img::after { background-color: UserColor}`

```css
img {
  font-family: "Helvetica";
  font-weight: 300;
  line-height: 1px;
  text-align: center;
  font-size: 1px;

  width: 24px;
  height: 24px;
  display: block;
  position: relative;
  border-radius: 50%;
}

img:empty {
  padding: 5px;
}

img::before {
  line-height: 32px;
  font-size: 16px;
  content: attr(alt);
  display: block;
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  margin: 0;
  font-style: normal;
  font-weight: 600;
  border-radius: 50%;

  text-align: center;
  text-decoration: none;
  text-transform: uppercase;
  background-color: inherit;
  color: var(--iui-color-foreground-accessory);
}
```
