### ISSUE TITLE
Active tab have different behaviors for fill and color

### ISSUE THREAD

**Issue by raplemie** [iTwin/iTwinUI#130]
#### Environment
- __Package version(s)__: css 0.16.0, react 1.5.0
- __Operating System__: Windows
- __Browser name and version__: Chrome, rather up to date.

#### Code Sandbox
Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/itwinui-react-example-son74)): 

#### Steps to reproduce

React:
```JSX
      <HorizontalTabs
        labels={[
          <span className={"tab-with-icon"} key="favorite">
            <SvgStarHollow />
            <p>Favorite projects</p>
          </span>,
          <span className={"tab-with-icon"} key={"recents"}>
            <SvgCalendar />
            <p>Recent projects</p>
          </span>,
          <span className={"tab-with-icon"} key={"all"}>
            <SvgList />
            <p>My projects</p>
          </span>,
        ]}
        onTabSelected={()=> alert("SELECTED");}
        activeIndex={0}
        type={"borderless"}
      >

```
CSS:
```css
.tab-with-icon {
  display: flex;
  flex-direction: row;
  align-items: center;
  gap: 11px;

  svg {
    height: 16px;
    width: 16px;
    //fill: currentColor; <-- Uncommenting this for a workaround.
  }
}
```

#### Actual behavior
The fill color is changing depending on hover state when tab is active, however the text color is not.

#### Expected behavior
I expected the icon to have the same color behavior than the text, hence the workaround of "currentColor".

As the color change is occuring without me adding anything, I did not expect to need to add something to "complete" the behavior.

#### Additional information
Here is a visual of what is happening, the fill is simply not overriden at the same place/conditions than the color is, so maybe the default behavior should simply be to apply `fill: currentColor` to the SVG instead of changing fill on top of color.

![vgwE605Q3T](https://user-images.githubusercontent.com/1904889/120541644-2067bb80-c3b8-11eb-94da-d71382616997.gif)
