### ISSUE TITLE
Icon: fix padding between icons

### ISSUE THREAD

**Issue by gretanausedaite** [iTwin/iTwinUI#1520]
Imagine `*` is an icon and `.` is a space.
We want a list of icons to be something like this:

`. . * . . * . . * . .` 

To achieve this we need to update icon css code.

**Comment by mayank99** [comment]
some code that i was playing around:
```scss
padding-inline: var(--_iui-svg-padding-inline);

+ & {
  padding-inline-start: 0;
}
```

**Comment by FlyersPh9** [comment]
I'm thinking the values should match [the borderless button's `--_iui-button-padding-inline`](https://github.com/iTwin/iTwinUI/blob/ddafcdde472a9a4009864c0471a310fb0b3219c7/packages/itwinui-css/src/button/base.scss#L94) for each size.

Small:
```scss
--_iui-button-padding-inline: var(--iui-size-2xs);
```

Medium:
```scss
--_iui-button-padding-inline: var(--iui-size-xs);
```

Large:
```scss
--_iui-button-padding-inline: var(--iui-size-s);
```

**Comment by mayank99** [comment]
@FlyersPh9  That was the initial thought but it looks inconsistent when multiple paddings get combined.

Since this issue is mainly for [InputWithDecorations](https://itwin.github.io/iTwinUI/dev/react/?path=/story/input-inputwithdecorations--basic)/[SearchBox](https://itwin.github.io/iTwinUI/dev/react/?path=/story/input-searchbox--basic), can you verify the values and show (visually) the spacing for:
- the leftmost/rightmost icons and the border
- the gap between two adjacent icons
- the padding between leftmost/rightmost icon and input text

I think it's ok if we need to diverge from the borderless button padding to make some of these gaps look nicer.

**Comment by FlyersPh9** [comment]
> That was the initial thought but it looks inconsistent when multiple paddings get combined.

[Your suggestion above](https://github.com/iTwin/iTwinUI/issues/1520#issuecomment-1695870778) wouldn't solve this?  Something like:

```scss
&[data-iui-size='small'] {
  --_iui-svg-padding-inline: var(--iui-size-2xs);
}

&[data-iui-size='medium'] {
  --_iui-svg-padding-inline: var(--iui-size-xs);
}

&[data-iui-size='large'] {
  --_iui-svg-padding-inline: var(--iui-size-s);
}

+ & {
  padding-inline-start: 0;
}
```
