### ISSUE TITLE
Hover state becomes stuck after tap on iOS

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#1827]
#### Describe the bug (actual behavior)

When tapping a button on iOS, the button gets stuck in the `:hover` state.  This likely effects all components that have a `:hover` state & after interaction you stay on the same page.

#### Reproduction

1. Open https://itwin.github.io/iTwinUI/css/button.html on iOS.
2. Tap button.

#### Additional information

I discovered this bug while working on a personal project and learned that [this solution fixes the issue](https://css-tricks.com/solving-sticky-hover-states-with-media-hover-hover/):
```scss
@media (hover: hover) {
  button:hover {
    border: 3px solid green;
  }
}
```
