### ISSUE TITLE
ExpandableBlock V2 vs. V3 display differences due to change from flex to grid layout

### ISSUE THREAD

**Issue by toddsouthenbentley** [iTwin/iTwinUI#2144]
### Describe the bug (current behavior)

We have a V2 react component that isn't displaying correctly in V3. This shared component is used by a few different consumers so it can't yet be upgraded to V3.
 
Specifically, we have some expandable block content that includes an Anchor element that could be potentially very long. To mitigate this, we truncate it using the following CSS:

```CSS
    // Truncate model path
    .gsr-outside-model-path {
      text-overflow: ellipsis;
      overflow: hidden;
      white-space: nowrap;
      width: 100%;
      font-size: var(--iui-font-size-0);
    }
```

Unfortunately this does not work in iTwinUI V3 (the link text isn't truncated to the parent width) but can be fixed if I add a column template for the grid:
 
```CSS
:where(._iui3-expandable-block[data-iui-expanded=true]) ._iui3-expandable-content {
  grid-template-columns: minmax(0, 1fr);
}
```

### Expected Behavior

The grid-template-columns should be part of iTwin's CSS.
