### ISSUE TITLE
Input type=datetime with dark theme look off.

### ISSUE THREAD

**Issue by maxime4000** [iTwin/iTwinUI#319]
![image](https://user-images.githubusercontent.com/4070713/136102438-5627c8c2-4e98-49be-bd45-a9a45e1fe230.png)

#### Steps to reproduce
I think it is cause because when min max does not allow to change Date, the text get grey's out, I don't think iTwinUI does support those style which cause dark theme unreadable. I was able to Edit as html backstop's text-field file and paste the problematic input.

```html
<input class="iui-input iui-small" type="datetime-local" max="2021-10-05T00:00:00" value="2021-10-04T00:00:00">
// The input below is showing the issue.
<input class="iui-input iui-small" type="datetime-local" min="2021-10-04T00:00:00" max="2021-10-05T17:03:42" value="2021-10-05T00:00:00">
```

**Comment by mayank99** [comment]
Not sure this should be handled on our end, because it's the theming of browser-provided elements and we don't currently fully support `input type=datetime`. You can kinda fix this by setting [`color-scheme: dark light`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme), but it's still not ideal.

You could target some vendor properties like so:
```scss
input {
  &::-webkit-datetime-edit-text,
  &::-webkit-datetime-edit-month-field,
  &::-webkit-datetime-edit-day-field,
  &::-webkit-datetime-edit-year-field {
    color: var(--iui-text-color);
  }
}
```
but that change will always apply regardless of `min`/`max`, so again it may not be ideal.

**Comment by maxime4000** [comment]
Well Webkit is part of chrome and support on chrome is essential IMO. I did improve the scss to fix disable field. Though, after some research, Chrome hasn't support for that. I found an old issues about the same problems in 2016. I made an new issues about it, hoping they will reconsider this old issue. While this SCSS is not working for disabled state, the style is removing disable color so dark theme shouldn't be unreadable. Plus if my issue get fix, disabled would now work with muted text color.
```scss
input {
  &::-webkit-datetime-edit-text,
  &::-webkit-datetime-edit-month-field,
  &::-webkit-datetime-edit-day-field,
  &::-webkit-datetime-edit-year-field {
    color: t(iui-text-color);
    &[disabled] { // In the hope they remove the limitation someday !
      color: t(iui-text-color-muted);
    }
  }
}
```
