### ISSUE TITLE
Last row in table when expanded then need to be scrolled

### ISSUE THREAD

**Issue by anandgaikwad** [iTwin/iTwinUI#473]
Now :
![image](https://user-images.githubusercontent.com/36064808/153003782-702aa750-c1d4-4407-85bb-7233311a7da7.png)

Should be like this when last row expanded

![image](https://user-images.githubusercontent.com/36064808/153003954-755e5b63-ee15-4acb-a21f-b803651e6e48.png)

**Comment by FlyersPh9** [comment]
I'm thinking we might be able to solve this by doing something like:
```scss
.iui-expanded-content:last-child {
  scroll-snap-align: end none;
}
```
