### ISSUE TITLE
Modal support of icon

### ISSUE THREAD

**Issue by pranaykute06** [iTwin/iTwinUI#586]
#### Feature
Add support for icon in the modal.

User can provide the required icon if they want to.

such modal can be used for delete confirmation etc....

#### Examples
![image](https://user-images.githubusercontent.com/82197220/162974880-4daaa9d2-68ee-4a5e-947e-10c3eb8f69ae.png)

![image](https://user-images.githubusercontent.com/82197220/162974904-6be3fa47-94ac-4327-af8e-79e45b7f5960.png)

**Comment by mayank99** [comment]
Hi @pranaykute06, thanks for the issue.

This would be a(nother) great use case for a generic "text with icon" component. I don't think we would want to add any modal-specific CSS for this.

@FlyersPh9 What is the correct spacing that should be applied here?

**Comment by FlyersPh9** [comment]
Areas that I think could make use of the icon + text + right aligned stuff that I can think of:
- Information panel title bar
- Modal title bar
- Expandable block title bar
- Menu items

I would probably replicate what is present in information panel, which is an 8px gap using `$iui-s`.
![Screen Shot 2022-04-12 at 5 43 22 PM](https://user-images.githubusercontent.com/849817/163059424-1fe9ba4a-a054-4b55-b918-00e2fc634834.png)

**Comment by FlyersPh9** [comment]
A mixin like this could be reused in a lot of the places I mentioned in my last comment:
```scss
@mixin iui-title-bar($title-bar-label-font-size: $iui-font-size-subheading, $title-bar-sublabel-font-size: $iui-font-size-small) {
  justify-content: space-between;

  &,
  &-left,
  &-right {
    display: flex;
    align-items: center;
  }

  &-left,
  &-right {
    gap: $iui-s;
  }

  &-icon {
    display: flex;
    width: $iui-icons-default;
    height: $iui-icons-default;
    @include themed {
      fill: t(iui-icons-color);
    }
  }

  &-title {
    display: flex;
    flex-direction: column;
    flex: auto;
    min-width: 0;
    @include themed {
      color: t(iui-color-foreground-body);
    }

    &-label,
    &-sublabel {
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    &-label {
      font-size: $title-bar-label-font-size;
      @include themed {
        opacity: t(iui-opacity-2);
      }
    }

    &-sublabel {
      font-size: $title-bar-sublabel-font-size;
      @include themed {
        opacity: t(iui-opacity-3);
      }
    }
  }
}
```

**Comment by mayank99** [comment]
> A mixin like this could be reused in a lot of the places I mentioned in my last comment:

Mixin is still too low level imo (it's an implementation details that gets "compiled" away). We should offer a simple class and component that the user can place anywhere. Nothing fancy, just this should be enough:

```css
.iui-text-with-icon {
  display: flex;
  align-items: center;
  gap: $iui-s;

  &-icon {
    @include iui-icons-default;
    flex-shrink: 0;
  }

  &-text {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
}
```

We already have classes for `iui-icons-default` available to the user, which we might even want to expose as a component in react. As for sublabel support, that can come in the future as it's not relevant to this issue.
