### ISSUE TITLE
[V1] Button refactor

### ISSUE THREAD

**Issue by veekeys** [iTwin/iTwinUI#605]
- [ ] split-menu rename to split-button

- [ ] specificity max 0.3.0

- [ ] have single class versus modifiers (i.e. iui-button-high-visibility))

- [ ] Icon button component. Should be square

- [ ] Button group sub components 

- [ ] Borderless active button needs active stripe

**Comment by mayank99** [comment]
Something we might want to think about is how to make our mixins smaller, as we reuse them in several other components.

In #568, @FlyersPh9 added a `iui-button-active` mixin but it only has _some_ of the active button styles, with the rest of them being located in `iui-button-borderless` and `iui-button-default` under the `&.iui-active` modifier.

**Comment by FlyersPh9** [comment]
How do we feel about this:
`<button class="iui-button" data-button-type="cta">`

Instead of this:
`<button class="iui-button iui-button-cta">`

Or this:
`<button class="iui-button-cta">`

>  have single class versus modifiers (i.e. iui-button-high-visibility))

This will result in a lot of duplicate CSS in the output.

**Comment by mayank99** [comment]
> How do we feel about this: `<button class="iui-button" data-button-type="cta">`

I like the data attribute but it should probably be prefixed with `-iui-`. Also might want to avoid the word "type" because its overused especially in JS. So something like `data-iui-button-variant` or even just `data-iui-variant`.

But one of the goals with this refactor should be to make it easier and less problematic to reuse the button styles in other components, so lets make sure this data attribute doesn't get in the way.

**Comment by FlyersPh9** [comment]
I have this within `borderless.scss` to achieve 1 / 1 aspect ratio for borderless buttons with only an icon:
```scss
.iui-button-icon:only-child {
  margin-left: 2px;
  margin-right: 2px;
}

&[data-iui-button-size='small'] .iui-button-icon:only-child {
  margin-left: 2.5px;
  margin-right: 2.5px;
}

&[data-iui-button-size='large'] .iui-button-icon:only-child {
  margin-left: 3.5px;
  margin-right: 3.5px;
}
```

The values are not good, but the values I think might be better once we change `$iui-baseline` to `12px`.

I was also trying this out as a solution for further in the future when [`:has` is better supported](https://caniuse.com/css-has) but unfortunately no luck:
```scss
@supports selector(:has(.iui-button-icon:only-child)) {
  :has(.iui-button-icon:only-child) {
    aspect-ratio: 1 / 1;
  }
}
```

If I implement the current solution we end up with 170 test image changes, 1 of which is broken because #680 hasn't been merged into the v1.0 branch yet.  **Should I commit this change or hold off until later?**
